### ISSUE TITLE
Coding Challenge 1

### ISSUE THREAD

**Issue by marecotec** [corbett-k/introduction#1]
Good stuff! Love your drone, check out some of our recent drone papers:

https://royalsocietypublishing.org/doi/10.1098/rspb.2021.0329

https://royalsocietypublishing.org/doi/10.1098/rspb.2019.2383

**Comment by corbett-k** [comment]
Thanks for sharing these!! 
I'd actually read the first one before landing at URI.  I'll be sure to check out the recent 2021 addition 👍 

I was sorta testing the waters of how to share this with you... so I still plan to add a bit more content prior to tomorrow's class. 
See you then!

**Comment by marecotec** [comment]
Good stuff, the 2021 paper is more of an application as opposed to the review that Tim did. If you like laser scanning as well, then Tim, my former student, was working on another interesting one, not quite birds, but I think its pretty interesting: https://zslpublications.onlinelibrary.wiley.com/doi/10.1002/rse2.213
